### ISSUE TITLE
No option to set duration of sendActionBar

### ISSUE THREAD

**Issue by MrVoltz** [ConnorLinfoot/BountifulAPI#1]
ActionBarAPI: ActionBarAPI.sendActionBar(player,"Action Bar Message", duration);
BountifulAPI: BountifulAPI.sendActionBar(player,"Action Bar Message");

**Comment by ConnorLinfoot** [comment]
Now Included in BountifulAPI V1.4 https://www.spigotmc.org/resources/bountifulapi.1394/download?version=60962
