### ISSUE TITLE
Delay not working for setTitle

### ISSUE THREAD

**Issue by ghost** [ConnorLinfoot/BountifulAPI#2]
I'm using: 
BountifulAPI.sendTitle(ply,200,200,200,"top","bottom");
but it will only stay for about 3 seconds and then it will fade out.
Thanks. (Sorry if I have been using the method incorrectly)

BountifulAPI version: 1.3
Spigot / Bukkit version: 1.8.8-R0.1

**Comment by ConnorLinfoot** [comment]
Doesn't seem like you're not doing anything wrong, just tried it myself and having the same issue.

Seem's like for some reason the packet sent with the time's don't actually get used by the server (Not sure if this has always been a thing and I've never fully tested it)

I'll work on getting an update out sometime today which should hopefully fix this.

**Comment by ConnorLinfoot** [comment]
Fixed in BountifulAPI V1.4 https://www.spigotmc.org/resources/bountifulapi.1394/download?version=60962
